version: '3.8'

services:
  # Сервис базы данных
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql

  # Сервис приложения
  app:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Server=DESKTOP-PBHMVB5;Database=larionov_3;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"

volumes:
  db-data: